name: 'Reusable Terraform CI'

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Directory containing the Terraform root module'
        required: true
        type: string
        default: '.'
      tf_version:
        description: 'Terraform CLI version'
        required: false
        type: string
        default: 'latest'
      tfvars_paths:
        description: 'JSON array of paths to .tfvars files (relative to working_directory)'
        required: false
        type: string
        default: '[]'
      terraform_backend_key:
        description: 'The name/path of the terraform state file within the backend container'
        required: true
        type: string
      environment_name:
        description: 'Name of the pre-configured GitHub Plan Environment for PR checks'
        required: true
        type: string

    secrets:
      AZURE_CLIENT_ID:
        description: 'Azure Client ID for OIDC'
        required: true
      AZURE_TENANT_ID:
        description: 'Azure Tenant ID for OIDC'
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: 'Azure Subscription ID for OIDC identity'
        required: true
      BACKEND_SUBSCRIPTION_ID:
        description: 'Subscription ID where the Terraform state storage account resides'
        required: true
      BACKEND_RESOURCE_GROUP_NAME:
        description: 'Resource Group name of the Terraform state storage account'
        required: true
      BACKEND_STORAGE_ACCOUNT_NAME:
        description: 'Storage Account name for Terraform state'
        required: true
      BACKEND_STORAGE_CONTAINER_NAME:
        description: 'Storage Container name for Terraform state'
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validate_and_plan:
    name: 'Terraform Validate & Plan (${{ inputs.environment_name }})'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    env:
      ARM_USE_OIDC: true
      ARM_USE_AZUREAD: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_IN_AUTOMATION: true
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.tf_version }}
          terraform_wrapper: false

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init (Validation)
        id: init_validate
        run: terraform init -backend=false

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Azure Login using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Terraform Init (with Backend)
        id: init
        run: |
          backend_args=""
          backend_args="$backend_args -backend-config=subscription_id=${{ secrets.BACKEND_SUBSCRIPTION_ID }}"
          backend_args="$backend_args -backend-config=resource_group_name=${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}"
          backend_args="$backend_args -backend-config=storage_account_name=${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}"
          backend_args="$backend_args -backend-config=container_name=${{ secrets.BACKEND_STORAGE_CONTAINER_NAME }}"
          backend_args="$backend_args -backend-config=key=${{ inputs.terraform_backend_key }}"
          backend_args="$backend_args -backend-config=use_oidc=true"

          echo "Running: terraform init -input=false $backend_args"
          terraform init -input=false $backend_args
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Plan
        id: plan
        run: |
          plan_args="-input=false -out=tfplan -detailed-exitcode"
          tfvars_paths_json='${{ inputs.tfvars_paths }}'
          if [[ -n "$tfvars_paths_json" && "$tfvars_paths_json" != "[]" ]]; then
            while IFS= read -r tfvar_path; do
              if [[ -n "$tfvar_path" ]]; then
                plan_args="$plan_args -var-file=$tfvar_path"
              fi
            done < <(echo "$tfvars_paths_json" | jq -r '.[]')
          fi
          set +e
          echo "Running: terraform plan $plan_args"
          terraform plan $plan_args
          exitcode=$?
          set -e
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          if [ $exitcode -eq 1 ]; then
            echo "::error::Terraform Plan Failed!"
            exit 1
          fi

      - name: Create Plan Output for Summary/PR Comment
        id: plan-output
        if: steps.plan.outputs.exitcode == '0' || steps.plan.outputs.exitcode == '2'
        run: |
          PLAN_OUTPUT=$(terraform show -no-color tfplan)
          PLAN_OUTPUT="${PLAN_OUTPUT//'%'/'%25'}"
          PLAN_OUTPUT="${PLAN_OUTPUT//$'\n'/'%0A'}"
          PLAN_OUTPUT="${PLAN_OUTPUT//$'\r'/'%0D'}"
          echo "plan_text<<EOF" >> $GITHUB_OUTPUT
          echo '```terraform' >> $GITHUB_OUTPUT
          terraform show -no-color tfplan >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          COMMENT_BODY="## Terraform Plan (${{ inputs.environment_name }})\n\n**Working Directory:** \`${{ inputs.working_directory }}\`\n**Plan Result:** $(if [ ${{ steps.plan.outputs.exitcode }} -eq 0 ]; then echo 'No Changes'; else echo 'Changes Detected'; fi)\n\n<details><summary>Click to expand Terraform Plan Output</summary>\n\n\`\`\`terraform\n$(terraform show -no-color tfplan)\n\`\`\`\n</details>"
          COMMENT_BODY="${COMMENT_BODY//'%'/'%25'}"
          COMMENT_BODY="${COMMENT_BODY//$'\n'/'%0A'}"
          COMMENT_BODY="${COMMENT_BODY//$'\r'/'%0D'}"
          echo "comment_body=$COMMENT_BODY" >> $GITHUB_OUTPUT

      - name: Publish Terraform Plan to Task Summary
        if: steps.plan.outputs.exitcode == '0' || steps.plan.outputs.exitcode == '2'
        env:
          PLAN_SUMMARY: ${{ steps.plan-output.outputs.plan_text }}
        run: |
          echo "## Terraform Plan Summary (${{ inputs.environment_name }})" >> $GITHUB_STEP_SUMMARY
          echo "**Working Directory:** \`${{ inputs.working_directory }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Plan Result:** $(if [ ${{ steps.plan.outputs.exitcode }} -eq 0 ]; then echo 'No Changes'; else echo 'Changes Detected'; fi)" >> $GITHUB_STEP_SUMMARY
          echo "<details><summary>Click to expand Plan Output</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "${PLAN_SUMMARY}" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Push Terraform Output to PR Comment
        if: github.event_name == 'pull_request' && (steps.plan.outputs.exitcode == '0' || steps.plan.outputs.exitcode == '2')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = decodeURIComponent("${{ steps.plan-output.outputs.comment_body }}");
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });